name: test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # for coverage
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - run: make tidy
    - name: Check if working tree is dirty
      run: |
        if [[ $(git diff --stat) != '' ]]; then
          git --no-pager diff
          echo 'run make tidy and commit changes'
          exit 1
        fi
    - run: make test
    - run: make docker-build
    - name: Helm lint
      run: |
        ci_version="0.1.0"
        sed -i "s/CI_VERSION/${ci_version}/g" charts/mcp-oauth2-proxy/Chart.yaml
        helm lint charts/mcp-oauth2-proxy
        helm package charts/mcp-oauth2-proxy
    - uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5.5.0
      with:
        use_oidc: true
        fail_ci_if_error: true
