name: test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - run: make tidy
    - name: Fail if working tree is dirty
      run: |
        git diff --exit-code || (echo "Working tree is dirty" && exit 1)
        git ls-files --others --exclude-standard | grep . && (echo "New untracked files were created" && exit 1)
    - run: make test
    - run: make docker-build
