name: test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - run: make tidy
    - name: Check if working tree is dirty
      run: |
        if [[ $(git diff --stat) != '' ]]; then
          git --no-pager diff
          echo 'run make tidy and commit changes'
          exit 1
        fi
    - run: make test
    - run: make docker-build
